name: tkbk
description: "A new Flutter project."
publish_to: 'none'

# Version: Remember to update before release!
version: 1.0.1+4 # Or your current version

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.11
  shared_preferences: ^2.5.3
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  # flutter_native_splash dependency (should already be here)
  flutter_native_splash: ^2.4.1 # Or your current version

flutter:
  uses-material-design: true

  assets:
    - assets/songs.json
    - assets/logo.png
    - assets/logo_1.png
    - assets/icon/app_icon.png # Keep if used elsewhere
    - assets/branding_text.png # <-- ADDED DECLARATION for branding image
    - assets/fonts/ # Font directory

  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
  - family: Open Sans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf

# flutter_launcher_icons config (ensure image_path points to your desired app icon source)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Or assets/icon/app_icon.png
  min_sdk_android: 21
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

# flutter_native_splash config (updated)
flutter_native_splash:
  # White background color
  color: "#FFFFFF"
  # Optional dark mode color
  # color_dark: "#1A237E"

  # Main logo image (centered)
  image: assets/logo_1.png # Or assets/icon/app_icon.png if you prefer

  # Branding text image (at bottom)
  branding: assets/branding_text.png # <-- ADDED branding property
  branding_mode: bottom # Position branding at the bottom

  # Platform toggles
  android: true
  ios: true

  # Android 12 config (uses main image/color if not specified)
  android_12:
    color: "#FFFFFF"
    image: assets/logo_1.png # Or assets/icon/app_icon.png