// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmRgL1f-c3Wj7ezoS5QPvkv4SZZ1RlyE',
    appId: '1:371710579657:web:50dc0cb8b34ad3ac4f4e18',
    messagingSenderId: '371710579657',
    projectId: 'apatani-biisi-kheta',
    authDomain: 'apatani-biisi-kheta.firebaseapp.com',
    storageBucket: 'apatani-biisi-kheta.firebasestorage.app',
    measurementId: 'G-RQH76B0KYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxjpD_8YtC5WxstJLu_D9Zjcxrn3h8wRA',
    appId: '1:371710579657:android:19031f39eec4a3514f4e18',
    messagingSenderId: '371710579657',
    projectId: 'apatani-biisi-kheta',
    storageBucket: 'apatani-biisi-kheta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Z3ENEDA3te1vYjn5rsPua_g3mSxAzlY',
    appId: '1:371710579657:ios:7b3a5a804e55bd2a4f4e18',
    messagingSenderId: '371710579657',
    projectId: 'apatani-biisi-kheta',
    storageBucket: 'apatani-biisi-kheta.firebasestorage.app',
    iosBundleId: 'com.example.tkbk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Z3ENEDA3te1vYjn5rsPua_g3mSxAzlY',
    appId: '1:371710579657:ios:7b3a5a804e55bd2a4f4e18',
    messagingSenderId: '371710579657',
    projectId: 'apatani-biisi-kheta',
    storageBucket: 'apatani-biisi-kheta.firebasestorage.app',
    iosBundleId: 'com.example.tkbk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHmRgL1f-c3Wj7ezoS5QPvkv4SZZ1RlyE',
    appId: '1:371710579657:web:4222e992f2e53e7f4f4e18',
    messagingSenderId: '371710579657',
    projectId: 'apatani-biisi-kheta',
    authDomain: 'apatani-biisi-kheta.firebaseapp.com',
    storageBucket: 'apatani-biisi-kheta.firebasestorage.app',
    measurementId: 'G-XGEMZYJ7FH',
  );
}
